import type { Metadata } from 'next'
import React from 'react'
import './globals.css'
import * as stylex from '@stylexjs/stylex'
import { fonts } from '../styles/globalTokens.stylex'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body {...stylex.props(styles.body)}>{children}</body>
    </html>
  )
}
const styles = stylex.create({
  body: {
    fontFamily: fonts.roboto,
    fontWeight: 300,
  },
})
